SEQUENCE {
  INTEGER 1
  SEQUENCE {
    SEQUENCE {
      OBJECT IDENTIFIER sha-256 (2 16 840 1 101 3 4 2 1)
      NULL
      }
    OCTET STRING
      DD 94 71 EF E7 43 C4 05 13 35 DF 8F 6D 28 82 F3
      BA DC 38 77 00 F7 ED 3F 70 91 67 2A 3E EA F7 C8
    }
  BOOLEAN TRUE
  }
